In [19]:
import pandas as pd

df = pd.read_csv("Love Birds.txt", header=None, delimiter="-", names=["Date", "LoveBirds", "Chat1","Chat2"])
df

,Date,LoveBirds,Chat1,Chat2
0,"10/22/25, 4:40 PM",Messages and calls are end,to,end encrypted. Only people in this chat can re...
1,"10/22/25, 6:53 PM","Somuadina Okoli: Hi Betty, good evening🙂",NaN,NaN
2,Hope you had enough rest?,NaN,NaN,NaN
3,"To be honest, I counted it as a privilege to b...",NaN,NaN,NaN
4,"10/22/25, 6:59 PM","Somuadina Okoli: Granted, I or any of your br...",NaN,NaN
...,...,...,...,...
19183,"3/23/26, 4:12 PM",Special ♥️: Alright,NaN,NaN
19184,"3/23/26, 4:19 PM",Special ♥️: I loveeeee youuuuu😘,NaN,NaN
19185,"3/23/26, 4:19 PM",Special ♥️: 💞💕💞💕💞💕💞,NaN,NaN
19186,"3/23/26, 4:20 PM",Special ♥️: <Media omitted>,NaN,NaN
19187,"3/23/26, 4:23 PM",Somuadina Okoli: 🥰,NaN,NaN

In [20]:
# Extracting the chats from the date column
Chat3 = pd.Series([n if not n[0].isdigit() else None for n in df.Date])

df["Chat"] = Chat3
df.head(20)

nDate = pd.Series([n if n[0].isdigit() else None for n in df.Date])
df["Date"] = nDate
df.head(10)

,Date,LoveBirds,Chat1,Chat2,Chat
0,"10/22/25, 4:40 PM",Messages and calls are end,to,end encrypted. Only people in this chat can re...,NaN
1,"10/22/25, 6:53 PM","Somuadina Okoli: Hi Betty, good evening🙂",NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,Hope you had enough rest?
3,NaN,NaN,NaN,NaN,"To be honest, I counted it as a privilege to b..."
4,"10/22/25, 6:59 PM","Somuadina Okoli: Granted, I or any of your br...",NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,"However, Jehovah has full knowledge and even ..."
6,NaN,NaN,NaN,NaN,So continue to maintain a good spiritual routi...
7,"10/22/25, 7:02 PM","Somuadina Okoli: Also, key into the slightest...",NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,"By the way, you and Jamin's photos are very nice."
9,NaN,NaN,NaN,NaN,Do send my regards to your mother and to him a...

In [21]:
# Cleaning the LoveBirds column
newdf = pd.Series(df["LoveBirds"])

df["Messages"] = newdf.apply(lambda x: str(x).split(":")[-1])
df["LoveBirds"] = df["LoveBirds"].apply(lambda x: str(x).split(":")[0])
df.drop(index = 0, inplace = True)
df.head(20)
df.head()

,Date,LoveBirds,Chat1,Chat2,Chat,Messages
1,"10/22/25, 6:53 PM",Somuadina Okoli,NaN,NaN,NaN,"Hi Betty, good evening🙂"
2,NaN,nan,NaN,NaN,Hope you had enough rest?,nan
3,NaN,nan,NaN,NaN,"To be honest, I counted it as a privilege to b...",nan
4,"10/22/25, 6:59 PM",Somuadina Okoli,NaN,NaN,NaN,"Granted, I or any of your brothers and sister..."
5,NaN,nan,NaN,NaN,"However, Jehovah has full knowledge and even ...",nan

In [22]:
#Stripping the LoveBirds column
df["LoveBirds"] = df.LoveBirds.str.strip()
df.head(20)

,Date,LoveBirds,Chat1,Chat2,Chat,Messages
1,"10/22/25, 6:53 PM",Somuadina Okoli,NaN,NaN,NaN,"Hi Betty, good evening🙂"
2,NaN,nan,NaN,NaN,Hope you had enough rest?,nan
3,NaN,nan,NaN,NaN,"To be honest, I counted it as a privilege to b...",nan
4,"10/22/25, 6:59 PM",Somuadina Okoli,NaN,NaN,NaN,"Granted, I or any of your brothers and sister..."
5,NaN,nan,NaN,NaN,"However, Jehovah has full knowledge and even ...",nan
6,NaN,nan,NaN,NaN,So continue to maintain a good spiritual routi...,nan
7,"10/22/25, 7:02 PM",Somuadina Okoli,NaN,NaN,NaN,"Also, key into the slightest measures of conc..."
8,NaN,nan,NaN,NaN,"By the way, you and Jamin's photos are very nice.",nan
9,NaN,nan,NaN,NaN,Do send my regards to your mother and to him a...,nan
10,"10/22/25, 7:04 PM",Special ♥️,NaN,NaN,NaN,"Good evening, yeah I really appreciate that"
11,"10/22/25, 7:05 PM",Special ♥️,NaN,NaN,NaN,"Thanks, will keep on ny routine cause that’s ..."
12,"10/22/25, 7:05 PM",Special ♥️,NaN,NaN,NaN,"Sure, I’ll send your greetings"
13,NaN,nan,NaN,NaN,Do extend my to your mum and brother too,nan
14,"10/22/25, 7:08 PM",Somuadina Okoli,NaN,NaN,NaN,Yh.
15,NaN,nan,NaN,NaN,One more thing.....,nan
16,"10/22/25, 7:10 PM",Somuadina Okoli,NaN,NaN,NaN,God of Heaven🫢🫢😅😅😅
17,"10/22/25, 7:11 PM",Somuadina Okoli,NaN,NaN,NaN,I comot cap for you o😅😅
18,NaN,nan,NaN,NaN,"Abeg, let me save you before it is too late 😆😆",nan
19,"10/22/25, 7:15 PM",Special ♥️,NaN,NaN,NaN,"Uh huh, I’m listening to"
20,"10/22/25, 7:16 PM",Special ♥️,NaN,NaN,NaN,Please do oh

In [ ]:
# Dropping the irrelevant column
df.drop(columns="Chat2", inplace = True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19187 entries, 1 to 19187
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       16991 non-null  str
 1   LoveBirds  19187 non-null  str
 2   Chat1      81 non-null     str
 3   Chat       2196 non-null   str
 4   Messages   19187 non-null  str
dtypes: str(5)
memory usage: 749.6 KB

In [28]:
df.head()

,Date,LoveBirds,Chat1,Chat,Messages
1,"10/22/25, 6:53 PM",Somuadina Okoli,NaN,NaN,"Hi Betty, good evening🙂"
2,NaN,nan,NaN,Hope you had enough rest?,nan
3,NaN,nan,NaN,"To be honest, I counted it as a privilege to b...",nan
4,"10/22/25, 6:59 PM",Somuadina Okoli,NaN,NaN,"Granted, I or any of your brothers and sister..."
5,NaN,nan,NaN,"However, Jehovah has full knowledge and even ...",nan

In [35]:
# Merging the chat columns
df["Chat1"].astype("str") + df["Messages"].astype("str")
df["Messages"] =  df["Chat1"].str.cat([df["Messages"], df["Chat"]], sep = "", na_rep="").str.strip("nan")
df.drop(columns = ["Chat1", "Chat"], inplace = True)
df.head()

,Date,LoveBirds,Messages
1,"10/22/25, 6:53 PM",Somuadina Okoli,"Hi Betty, good evening🙂"
2,NaN,nan,Hope you had enough rest?
3,NaN,nan,"To be honest, I counted it as a privilege to b..."
4,"10/22/25, 6:59 PM",Somuadina Okoli,"Granted, I or any of your brothers and sister..."
5,NaN,nan,"However, Jehovah has full knowledge and even ..."

In [36]:
# The dataset will now be saved in a csv file, and be transported to power query for more structuring

df.to_csv("LoveBirds.csv", index=None)